{ pkgs, config, ... }:

{
  programs.lf = {

    enable = false;

    settings = {
      preview = true;
      ignorecases = true;
    };

    keybindings = {
      "." = "set hidden!";
      c = "yank-file";
      d = null;
      dd = "trash";
      dl = "dlfile";
      dr = "dragon";
      f = "broot_jump";
      h = "chmod";
      k = "down";
      l = "up";
      ";" = "open";
      j = "updir";
      m = null;
      md = "mkdir";
      mf = "mkfile";
      mr = "sudomkfile";
      Q = "quit-and-cd";
      u = "unarchive";
      x = "cut";
    };
  };

  #previewer = {
  #  keybinding = "i";
  #  source = "${pkgs.unstable.pistol}/bin/pistol";
  #};

  ## settings = {
  ##   icons = true;
  ##   # Set IFS to newline to allow commands to work with spaces in filenames
  ##   ifs = "\n";
  ## };

  ## home.sessionVariables = {
  ##   LF_ICONS = ''
  ##     tw=:\
  ##     st=:\
  ##     ow=:\
  ##     dt=:\
  ##     di=:\
  ##     fi=:\
  ##     ln=:\
  ##     or=:\
  ##     ex=:\
  ##     *.c=:\
  ##     *.cc=:\
  ##     *.clj=:\
  ##     *.coffee=:\
  ##     *.cpp=:\
  ##     *.css=:\
  ##     *.d=:\
  ##     *.dart=:\
  ##     *.erl=:\
  ##     *.exs=:\
  ##     *.fs=:\
  ##     *.go=:\
  ##     *.h=:\
  ##     *.hh=:\
  ##     *.hpp=:\
  ##     *.hs=:\
  ##     *.html=:\
  ##     *.java=:\
  ##     *.jl=:\
  ##     *.js=:\
  ##     *.json=:\
  ##     *.lua=:\
  ##     *.md=:\
  ##     *.php=:\
  ##     *.pl=:\
  ##     *.pro=:\
  ##     *.py=:\
  ##     *.rb=:\
  ##     *.rs=:\
  ##     *.scala=:\
  ##     *.ts=:\
  ##     *.vim=:\
  ##     *.cmd=:\
  ##     *.ps1=:\
  ##     *.sh=:\
  ##     *.bash=:\
  ##     *.zsh=:\
  ##     *.fish=:\
  ##     *.tar=:\
  ##     *.tgz=:\
  ##     *.arc=:\
  ##     *.arj=:\
  ##     *.taz=:\
  ##     *.lha=:\
  ##     *.lz4=:\
  ##     *.lzh=:\
  ##     *.lzma=:\
  ##     *.tlz=:\
  ##     *.txz=:\
  ##     *.tzo=:\
  ##     *.t7z=:\
  ##     *.zip=:\
  ##     *.z=:\
  ##     *.dz=:\
  ##     *.gz=:\
  ##     *.lrz=:\
  ##     *.lz=:\
  ##     *.lzo=:\
  ##     *.xz=:\
  ##     *.zst=:\
  ##     *.tzst=:\
  ##     *.bz2=:\
  ##     *.bz=:\
  ##     *.tbz=:\
  ##     *.tbz2=:\
  ##     *.tz=:\
  ##     *.deb=:\
  ##     *.rpm=:\
  ##     *.jar=:\
  ##     *.war=:\
  ##     *.ear=:\
  ##     *.sar=:\
  ##     *.rar=:\
  ##     *.alz=:\
  ##     *.ace=:\
  ##     *.zoo=:\
  ##     *.cpio=:\
  ##     *.7z=:\
  ##     *.rz=:\
  ##     *.cab=:\
  ##     *.wim=:\
  ##     *.swm=:\
  ##     *.dwm=:\
  ##     *.esd=:\
  ##     *.jpg=:\
  ##     *.jpeg=:\
  ##     *.mjpg=:\
  ##     *.mjpeg=:\
  ##     *.gif=:\
  ##     *.bmp=:\
  ##     *.pbm=:\
  ##     *.pgm=:\
  ##     *.ppm=:\
  ##     *.tga=:\
  ##     *.xbm=:\
  ##     *.xpm=:\
  ##     *.tif=:\
  ##     *.tiff=:\
  ##     *.png=:\
  ##     *.svg=:\
  ##     *.svgz=:\
  ##     *.mng=:\
  ##     *.pcx=:\
  ##     *.mov=:\
  ##     *.mpg=:\
  ##     *.mpeg=:\
  ##     *.m2v=:\
  ##     *.mkv=:\
  ##     *.webm=:\
  ##     *.ogm=:\
  ##     *.mp4=:\
  ##     *.m4v=:\
  ##     *.mp4v=:\
  ##     *.vob=:\
  ##     *.qt=:\
  ##     *.nuv=:\
  ##     *.wmv=:\
  ##     *.asf=:\
  ##     *.rm=:\
  ##     *.rmvb=:\
  ##     *.flc=:\
  ##     *.avi=:\
  ##     *.fli=:\
  ##     *.flv=:\
  ##     *.gl=:\
  ##     *.dl=:\
  ##     *.xcf=:\
  ##     *.xwd=:\
  ##     *.yuv=:\
  ##     *.cgm=:\
  ##     *.emf=:\
  ##     *.ogv=:\
  ##     *.ogx=:\
  ##     *.aac=:\
  ##     *.au=:\
  ##     *.flac=:\
  ##     *.m4a=:\
  ##     *.mid=:\
  ##     *.midi=:\
  ##     *.mka=:\
  ##     *.mp3=:\
  ##     *.mpc=:\
  ##     *.ogg=:\
  ##     *.ra=:\
  ##     *.wav=:\
  ##     *.oga=:\
  ##     *.opus=:\
  ##     *.spx=:\
  ##     *.xspf=:\
  ##     *.pdf=:\
  ##     *.nix=:
  ##   '';
  ## };
}
